

Goldsite-${theme}
=============

This is GoldSite theme ${theme} generated by goldsite tools. Goldsite is an easy and quick web 5.0 website build tool.


这是一个GoldSite模板/皮肤${theme},它是由goldsite tools工具生成的模板/皮肤。goldsite是一款简单快速开发基于Web5.0的建站工具